---
- name: Add quest-repo to install vasd
  yum_repository:
    name: quest
    description: Quest-repo
    file: quest
    baseurl: https://repo.corp.ru/repository/quest
    gpgcheck: no
    enabled: yes
    proxy: _none_
    sslverify: no


# Handler showing how to clean yum metadata cache
#- name: yum-clean-metadata
#  command: yum clean metadata
#  args:
#    warn: no


- name: Install "{{ packages }}"
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - vasgp
    - vasclnt
    - python3-pip


- name: Install "{{ packages }}" for old CentOS
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - python-pip
  ignore_errors: yes

- name: Install pexpect to passthrough password
  pip:
    name: pexpect>=3.3
    extra_args: --index-url https://repo.corp.ru/repository/pypi/simple/ --trusted-host=repo.corp.ru
    executable: pip3

- name: Install pexpect by pyhton2-pip for old CentOS 
  pip:
    name: pexpect>=3.3
    extra_args: --index-url https://repo.corp.ru/repository/pypi/simple/ --trusted-host=repo.corp.ru
  ignore_errors: yes


- name: Join to domain command
  expect:
    command: /opt/quest/bin/vastool -u user_join join -fws {{ AD_site_name }} -c ou=computers,ou=gk,dc=corp,dc=ru CORP.RU 
    responses:
      Password for user_join@CORP.RU: ""
  # you don't want to show passwords in your logs
  #no_log: true
  register: cat
  ignore_errors: yes

- debug: var=cat.stdout_lines
