---
- hosts: promo_web_nlb
  vars:
    - fqdn_to_locate: "https://pr.domain.ru"
    - hamaster: 10.5.45.97
    - habackup: 10.5.45.114
    - backend1: 10.5.45.117
    - backend2: 10.5.45.122
    #keepalived vars
    - keepalived_interface: "ens32"
    - virtual_router_id: 45
    - virtual_ipaddress: 10.5.45.204	

  roles: 
    - haproxy-keepalived
